name: Access Issue Information and Generate Code

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  process_issue:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot') # Check if the issue has the autocoder-bot label
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Make Script Executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $ISSUE_NUMBER $REPO $OPENAI_API_KEY

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: List Generated Files Recursively
        run: |
          echo "Listing files in autocoder-artifact directory:"
          ls -R autocoder-artifact/
